import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Denys Pupin - Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GAID!} />
        <SpeedInsights />
        <main className="px-6 md:px-12 lg:px-16 xl:px-32">{children}</main>
      </body>
    </html>
  );
}
